#!/bin/bash

#echo "please enter a name, and i will use that name to  create a directory for you: "



read -p  "please enter a name, and i will use that name to  create a directory for you: " dir



echo "creating a new directory for you now!"

mkdir ./$dir



echo "I just created a new directory for you called $dir, thank you!"
